### ISSUE TITLE
Compiled python files broken on python 3.6.1

### ISSUE THREAD

**Issue by Bob-Thomas** [aldewereld/practicum-atp#2]
Bad magic number.
probably caused because it's compiled by a different version of python
$ python main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from Simulator import Simulator
ImportError: bad magic number in 'Simulator': b'\x16\r\r\n'

**Comment by aldewereld** [comment]
c5f540a608556a56f830247273d48fc6d8f22703
