### ISSUE TITLE
One is not a prime

### ISSUE THREAD

**Issue by sqrtroot** [aldewereld/practicum-atp#4]
In the function `is_prime(n)` of assignment 1.1.1 in file `Practicum Testing.ipynb` the number 1 is considered a prime while it's not a prime

**Comment by aldewereld** [comment]
Which is correct by definition:
> The definition is as follows. 
> 
> An integer greater than one is called a prime number if its only positive divisors (factors) are one and itself.  

See [Why is the number one not prime? ](https://primes.utm.edu/notes/faq/one.html) for more reasons why 1 is not considered a prime...

**Comment by aldewereld** [comment]
The code is not ment to be correct; write tests and fix them! ;-)
