### ISSUE TITLE
importing function_demo and class_demo - using a "-" in filename

### ISSUE THREAD

**Issue by Bob-Thomas** [aldewereld/practicum-atp#5]
Don't think python appreciates a `-` or a `.` in a filename you want to import.
https://stackoverflow.com/questions/8350853/how-to-import-module-when-module-name-has-a-dash-or-hyphen-in-it

**Comment by aldewereld** [comment]
Good to know; I'll replace them  with underscores in a next version.

For now: rename the file appropriate for your interpreter (remove the '-3.5'/'-3.6' suffix from the file).

**Comment by aldewereld** [comment]
Fixed: 5c1d61818a8dd751ce937ab836f9786d717757ab
